service: tax-tools
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: tax-tools
  region: ${env:REGION}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ":"
          - - "arn:aws:s3::"
            - "${env:DATA_BUCKET}/*"
  environment:
    DATA_BUCKET: ${env:DATA_BUCKET}

functions:
  gross-up:
    handler: src/functions/gross-up.handler
    events:
      - http: GET /gross-up

  process-transaction:
    handler: src/functions/process-transaction.handler
    events:
      - http: POST /process-transaction
    environment:
      POT_ID: ${env:POT_ID}
      ACC_ID: ${env:ACC_ID}
      DEBUG: '*'